softeerbootcamp-2nd/A2-CarTag

frontend/src/containers/OptionPage/OptionBannerContainer.tsx, frontend/src/containers/OptionPage/OptionSelectContainer/ExtraOptionContainer copy.tsx
- 이미지 토스트 팝업 기능 구현
- main task: #93
close #93
close #110
close #111 
https://github.com/softeerbootcamp-2nd/A2-CarTag/assets/63107805/3aef0705-ce46-4cbd-8891-bd0cc427d75e
=> [FEAT] #111: 이미지 토스트 팝업 구현

frontend/src/containers/ResultPage/HistogramContainer/Histogram.tsx, frontend/src/containers/ResultPage/HistogramContainer/HistogramContainer.tsx, frontend/src/pages/ResultPage.tsx
- 막대 그래프
- 곡선 그래프 틀
- close #131 
곡선그래프는 나중에 작업할게요~!!!!!!!!
=> Feat/result page UI

backend/src/test/java/autoever2/cartag/repository/CarRepositoryTest.java
=> [TEST] #142: car bought count 테스트 구현

frontend/src/components/histogram/CurveHistogram.tsx
=> [FEAT] #148: 임시 데이터로 곡선 히스토그램 구현

frontend/src/components/histogram/CurveHistogram.tsx
=> [FIX] lint warning

frontend/src/components/histogram/CurveHistogram.tsx
=> [FIX] #157: dependancy warning 해결

frontend/src/components/layout/NavBar.tsx
=> [FIX] #161: 경로 오류 수정

backend/src/main/java/autoever2/cartag/domain/car/DefaultOptionDto.java, backend/src/main/java/autoever2/cartag/repository/CarRepository.java, backend/src/test/java/autoever2/cartag/controller/TrimControllerTest.java, backend/src/test/java/autoever2/cartag/service/CarServiceTest.java, backend/src/test/resources/insert/insertCar-h2.sql, backend/src/test/resources/schema-h2.sql
table의 필드명 수정으로 인한 query문을 수정합니다.
close #170
=> [BUGFIX] #170 : ERD 수정으로 인한 query관련 버그 수정

backend/src/main/java/autoever2/cartag/controller/OptionController.java, backend/src/main/java/autoever2/cartag/domain/suboption/SubOptionMappedDto.java, backend/src/main/java/autoever2/cartag/repository/CarRepository.java, backend/src/main/java/autoever2/cartag/repository/OptionRepository.java, backend/src/main/java/autoever2/cartag/service/CarService.java, backend/src/main/java/autoever2/cartag/service/OptionService.java, backend/src/test/java/autoever2/cartag/controller/SubOptionControllerTest.java, backend/src/test/java/autoever2/cartag/repository/CarRepositoryTest.java, backend/src/test/java/autoever2/cartag/repository/OptionRepositoryTest.java, backend/src/test/java/autoever2/cartag/service/CarServiceTest.java, backend/src/test/java/autoever2/cartag/service/OptionServiceTest.java, backend/src/test/resources/insert/insert-suboption-h2.sql, backend/src/test/resources/insert/insertCar-h2.sql
option 테이블 변경으로 query를 변경합니다.
테스트 코드와 repository를 하나의 option이 관리하도록 합니다.
close #174
=> [BUGFIX] # 174 기존의 option들을 하나의 option으로 통합

frontend/src/App.tsx, frontend/src/components/layout/NavBar.tsx, frontend/src/containers/Modal/ModalContainer.tsx
=> [REFACTOR] #177: ui 수정

frontend/src/components/layout/NavBar.tsx, frontend/src/components/pageAnimation/PageAnimationWrapper.tsx, frontend/src/components/priceStaticBar/PriceStaticBar.tsx, frontend/src/components/router/CustomRouter.tsx
`/` 경로 진입시 렌더링하는 컴포넌트가 없어 AnimatePresence에서 오류를 일으킴
`/` 경로로 진입 시에도 trim page를 렌더링하도록 변경함
=> [FIX] #188: AnimatePresence 에러 수정

frontend/.eslintignore, frontend/.husky/pre-commit, frontend/package-lock.json, frontend/package.json
```json
// package.json
"husky": "^8.0.3",
"lint-staged": "^13.2.3",
```
- commit 이나 push 발생시 지정된 명령 실행
- 현재는 commit 발생시 lint, format 설정 
- git add 된 파일에 대해서만 지정된 명령어 실행
```json
"lint-staged": {
"*.{js,jsx,ts,tsx}": [
"prettier --write .",
"eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0"
]
}
```
commit 발생시, 위 명령이 자동으로 실행됩니당
=> [CHORE] #192: 허스키 설정

backend/src/main/java/autoever2/cartag/controller/ModelController.java, backend/src/main/java/autoever2/cartag/domain/model/ModelDetailMappedDto.java, backend/src/main/java/autoever2/cartag/domain/model/ModelEfficiencyDataDto.java, backend/src/main/java/autoever2/cartag/domain/model/ModelShortDataDto.java, backend/src/main/java/autoever2/cartag/domain/suboption/SubOptionDto.java, backend/src/main/java/autoever2/cartag/repository/ModelRepository.java, backend/src/main/java/autoever2/cartag/service/ModelService.java, backend/src/test/java/autoever2/cartag/controller/ModelControllerTest.java, backend/src/test/java/autoever2/cartag/repository/ModelRepositoryTest.java, backend/src/test/java/autoever2/cartag/service/ModelServiceTest.java, backend/src/test/resources/insert/insert-model-h2.sql
연비와 배기량 HMG 데이터 호출 API 생성
- close : #35
=> 모델 타입 Efficiency HMG 데이터 처리

backend/src/main/java/autoever2/cartag/repository/OptionRepository.java, backend/src/test/java/autoever2/cartag/repository/OptionRepositoryTest.java
쿼리를 수정함으로써 상위 3개의 defaultoption을 반합니다.
- close : #198
=> [REFACTOR] #198 : 기존의 쿼리를 수정하여 defaultoption을 상위 3개만 반환하도록 수정합니다.

frontend/src/App.tsx, frontend/src/components/contextProviders/Providers.tsx
- Providers 컴포넌트 작성
```tsx
function App() {
return (
<CloseModalProvider>
<SimilarQuoteModalProvider>
<GuideModalProvider>
...
</GuideModalProvider>
</SimilarQuoteModalProvider>
</CloseModalProvider>
);
}
export default App;
```
```tsx
function App() {
const modalProviders = [CloseModalProvider, SimilarQuoteModalProvider, GuideModalProvider];
return (
<Providers contexts={modalProviders}>
...
</Providers>
);
}
```
`<Providers/>` 컴포넌트에 Provider를 배열로 넣어주면 됩니다.
=> [REFACTOR] #194: context api 중첩 제거

.github/backend/scripts/deploy.sh
=> [FEAT] #118 : deploy.sh 을 생성

.github/workflows/backend.yml
=> [FEAT] #118 : workflow를 생성합니다.

backend/appspec.yml
=> [FEAT] #118 자동 배포를 위한 appspec.yml 생성

backend/scripts/deploy.sh
=> [FEAT] #118 : spring boot 실행을 위한 script를 생성합니다.

frontend/src/components/priceStaticBar/PriceStaticBar.tsx
`Over 200 classes were generated for component styled.section. Consider using the attrs method, together with a style object for frequently changed styles.` 경고 해결
동적으로 attrs로 스타일 지정
=> [FIX] #205: 드래그 시 스타일 컴포넌트 많이 생기는 경고 해결

.github/workflows/frontend.yml
s3로 프론트 엔드 파일을 업로드 하기위한, workflow 작성
=> [FEAT] #118 : frontend workflow를 생성합니다.

.github/workflows/frontend.yml
=> [REFACTOR] #118 : frontend workflow 수정합니다.

backend/src/main/java/autoever2/cartag/WebConfig.java
www.a2cartag.com으로 배포되어있는 프론트엔드 CORS 문제 해결
- close : #218
=> [BUG FIX] #218: CORS 적용

backend/src/main/java/autoever2/cartag/WebConfig.java, backend/src/test/resources/schema-h2.sql
[www.a2cartag.com으로](http://www.a2cartag.xn--com-ky7m580d/) 배포되어있는 프론트엔드 CORS 문제 해결
- close: #218
=> [BUG FIX] #218: CORS 단일 URL에 대해서만 적용

backend/src/main/java/autoever2/cartag/repository/ModelRepository.java, backend/src/main/java/autoever2/cartag/service/ModelService.java
예외를 던지는 부분을 null로 변경
- close: #242 
```
return modelRepository.findPowerTrainData(powerTrainId).orElse(null);
```
=> [BUG FIX] #242: 프론트엔드 요청사항 반영하여 모델타입 HMG 데이터 반환 Null

backend/src/main/java/autoever2/cartag/WebConfig.java
프론트엔드 개발자 로컬 환경 테스트를 위한 와일드카드 개방
=> [BUG FIX] #218: CORS 로컬 환경 테스트를 위한 와일드카드 지정

frontend/src/components/priceStaticBar/PriceStaticBar.tsx, frontend/src/components/priceStaticBar/PriceStaticSlider.tsx
- keyframes 경고 해결
- 슬라이더 드래그 버그 해결
- main task: #245
=> [BUG FIX] #245: 예산 설정바 버그 해결

frontend/src/utils/constants.ts
=> [REFACTOR] #213: 한글 코드 변경

frontend/src/containers/ExteriorPage/ExteriorSelectContainer.tsx, frontend/src/containers/InteriorPage/InteriorSelectContainer.tsx, frontend/src/containers/OptionPage/OptionFooterContainer.tsx
=> [FIX] build error 수정

frontend/src/containers/TrimPage/TrimBannerContainer.tsx
=> [hotfix] 이미지 경로 문제 디버깅'

frontend/src/containers/TrimPage/TrimBannerContainer.tsx, frontend/src/utils/apis.ts
=> [hotfix] : debugging

frontend/src/containers/TrimPage/TrimBannerContainer.tsx, frontend/src/utils/apis.ts
=> [hotfix] debugging 종료

backend/src/main/java/autoever2/cartag/domain/model/ModelShortMappedDto.java, backend/src/main/java/autoever2/cartag/repository/ModelRepository.java, backend/src/test/java/autoever2/cartag/controller/OptionControllerTest.java, backend/src/test/java/autoever2/cartag/service/ModelServiceTest.java
HMG 데이터가 실제로 반환되지 않는 오류를 test 추가로 찾아 해결
=> [HOT FIX] 메인 버그 수정 및 테스트 개선

backend/src/main/java/autoever2/cartag/domain/model/PowerTrainDataDto.java
=> [BUG FIX] #273: Getter 부재로 serializable error 발생 해결

frontend/src/containers/InnerColorPage/InnerColorSelectContainer.tsx, frontend/src/containers/OuterColorPage/OuterColorSelectContainer.tsx
=> [FEAT] #220: 외장 색상 가격 반영

frontend/src/containers/ModelTypePage/ModelTypeSelectContainer.tsx
=> [BUG FIX] #292: 디폴트 값 반영되도록 해결

frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx, frontend/src/reducer/car360Reducer.ts
=> [BUGFIX] #294 : 360 image 로딩 버그 수정

frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx
=> [REFACTOR] #294: 함수 명 수정

frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx
=> [BUGFIX] #300: 360 이미지 버그 수정

frontend/src/components/cards/ModelTypeCard.tsx, frontend/src/components/cards/OuterColorCard.tsx, frontend/src/containers/TrimPage/TrimBannerContainer.tsx
=> [REFACTOR] #302: '회', ',' 붙이기

frontend/src/components/cards/OptionCard.tsx, frontend/src/components/common/banner/Banner.tsx, frontend/src/components/common/hmgTag/HmgTag.tsx, frontend/src/components/tabs/OptionTab.tsx, frontend/src/containers/OptionPage/OptionBannerContainer.tsx, frontend/src/containers/OptionPage/OptionSelectContainer/DefaultOptionContainer.tsx, frontend/src/containers/OptionPage/OptionSelectContainer/SubOptionContainer.tsx, frontend/src/utils/constants.ts
- 탭 간격 수정
- 콤마
- 글자 길 때
TODO
- 탭 호버할 때 텍스트
- 옵션 이름 길 때 뭔가 이상함 더 생각해야할듯
=> [FEAT] #295: 데모 대비 스냅샷

frontend/src/components/tabs/OptionTab.tsx
=> [REFACTOR] #295: 탭 display로 변경

frontend/src/components/cards/ModelTypeCard.tsx, frontend/src/components/cards/OptionCard.tsx, frontend/src/components/common/banner/Banner.tsx, frontend/src/components/tabs/OptionTab.tsx, frontend/src/containers/OptionPage/OptionSelectContainer/SubOptionContainer.tsx, frontend/src/context/ItemProvider.tsx
- 가격 적용
- 글자 크기 변경
- 탭에 key 부여
- close: #295 
TODO
1. 옵션 이름(배너) 길 때 예외 처리 안함
=> 배너 바꿔야 할 듯
2. 카드 선택하는거 바꿔야함
=> [FEAT] #295: 옵션 페이지 세부사항

frontend/src/App.tsx, frontend/src/components/common/buttons/ToggleButtons.tsx, frontend/src/components/details/Details.tsx, frontend/src/components/details/SummaryItem.tsx, frontend/src/components/modal/QuoteSummaryModal.tsx, frontend/src/components/modal/WhiteModal.tsx, frontend/src/components/summary/PriceSummary.tsx, frontend/src/containers/Modal/ModalContainer.tsx, frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx, frontend/src/containers/OuterColorPage/OuterColorSelectContainer.tsx, frontend/src/containers/ResultPage/DetailContainer.tsx, frontend/src/containers/ResultPage/ResultFooterContainer.tsx, frontend/src/context/ItemProvider.tsx, frontend/src/context/OuterColorProvider.tsx, frontend/src/context/QuoteSummaryModalProvider.tsx, frontend/src/pages/OuterColorPage.tsx
- UI 작성 완료
- 선택 값 연결 완료
차량 외부, 내부 이미지 없음
옵션은 더미 데이터
=> [FEAT] #316: 견적 요약 모달 창

frontend/src/components/modal/QuoteSummaryModal.tsx
=> [FEAT] #316:  견적요약 옵션 가격 반영

frontend/src/components/cards/OptionCard.tsx, frontend/src/components/common/buttons/RoundButton.tsx, frontend/src/components/details/SummaryItem.tsx, frontend/src/containers/InnerColorPage/InnerColorBannerContainer.tsx
- RectButton hover 수정
- 결과 페이지 이미지 url 오류 수정
- 옵션 페이지 이미지 비율 수정
- 내장 색상 페이지 배너 깜빡임 수정
=> [FEAT] #328: UI 수정

frontend/src/components/tabs/OptionTab.tsx, frontend/src/containers/OptionPage/OptionBannerContainer.tsx
탭 누를때 사진이랑 hmg데이터도 바뀌게 했어용
지금은 0번 보이는데 종원님이 Null로 바꾸면 안 보일것임
=> [FIX] #323: 탭 선택하면 해당 데이터로 수정

frontend/src/components/details/Details.tsx, frontend/src/components/details/DetailsItemList.tsx, frontend/src/containers/ModelTypePage/ModelTypeBannerContainer.tsx, frontend/src/containers/ResultPage/DetailContainer.tsx, frontend/src/context/ModelTypeProvider.tsx
- 모델 타입 페이지 Hmg Data 영역 움직이는 현상 수정
- 모델 타입 페이지 Hmg Data 콤마 찍기
- 결과 페이지, 옵션 많이 추가할 경우 짤리는 버그 수정
- 결과 페이지 코드 리팩토링
=> [FEAT] #332: 모델 타입 UI 수정, 결과페이지 리팩토링

backend/src/main/java/autoever2/cartag/domain/option/OptionDetailMappedDto.java
프론트엔드 요청사항에 따라 0이아닌 null반환하도록 변경
colorServiceTest 버그도 merge로 해결
- closes: #326
=> [BUG FIX] #326: 옵션 HMG 데이터 0이아닌 Null반환

frontend/src/components/modal/ErrorModal.tsx, frontend/src/containers/ModelTypePage/ModelTypeBannerContainer.tsx, frontend/src/containers/TrimPage/TrimBannerContainer.tsx, frontend/src/hooks/useFetch.ts, frontend/src/pages/InnerColorPage.tsx, frontend/src/pages/ModelTypePage.tsx, frontend/src/pages/OptionPage.tsx, frontend/src/pages/OuterColorPage.tsx, frontend/src/pages/TrimPage.tsx
- 서버 에러 생겼을 때, 모달 창 뜨게 처리
```tsx
const { data, loading, error } = useFetch<ICartype[]>(`${TRIM_API}?cartype=${1}`);
if (error) {
return <ErrorModal message={error.message} />;
}
```
=> [FEAT] error 처리

backend/src/main/java/autoever2/cartag/controller/CarController.java, backend/src/main/java/autoever2/cartag/service/RecommendService.java
=> [REFACTOR] #370 : 주석제거

frontend/src/containers/InnerColorPage/InnerColorFooterContainer.tsx, frontend/src/containers/InnerColorPage/InnerColorSelectContainer.tsx, frontend/src/containers/OuterColorPage/OuterColorFooterContainer.tsx, frontend/src/containers/OuterColorPage/OuterColorSelectContainer.tsx, frontend/src/containers/ResultPage/ResultBannerContainer.tsx, frontend/src/containers/ResultPage/ResultFooterContainer.tsx, frontend/src/pages/InnerColorPage.tsx, frontend/src/pages/OuterColorPage.tsx
=> [FEAT] #368: footer 아래에 고정

frontend/src/App.tsx, frontend/src/components/layout/NavBar.tsx, frontend/src/containers/TrimPage/TrimSelectContainer.tsx, frontend/src/context/ProgressProvider.tsx
- `ProgressProvider.tsx` 파일 생성했어요
=> [FEAT] #367: nav 바 트림 선택안하면 disable

frontend/src/components/priceStaticBar/PriceStaticSlider.tsx
```tsx
const PriceBar = styled.input.attrs
({ type, min, max, value, onChange, step, $percent, $isover }) => ({
style: {
background: `linear-gradient(
to right,
#fff 0%,
#fff ${$percent}%,
${$isover ? theme.color.gray800 : theme.color.primaryColor800} ${$percent}%,
${$isover ? theme.color.gray800 : theme.color.primaryColor800} 100%
)`,
},
```
요롷게 수정했음여
=> [FIX] #376: 예산 설정바 over 200 경고 해결

backend-recommend/app.py, backend-recommend/recommend.py
샘플 데이터수 100000개로 축소하여 메모리 초과문제 해결
- closes: #386
=> [REFACTOR] #386: 추천 알고리즘 성능 향상 및 메모리 초과 방지를 위해 샘플 데이터 축소

frontend/src/components/modal/QuoteSummaryModal.tsx, frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx, frontend/src/containers/TrimPage/TrimBannerContainer.tsx, frontend/src/pages/OuterColorPage.tsx
색상 마다 이미지 이름이 같아, 브라우저가 같은 이미지로 생각하여 캐싱된 이미지를 쓰려고함
-> 캐싱된 이미지를 요청할때는 요청 헤더에 origin 헤더가 없음
-> 캐싱된 이미지 응답 헤더에는 Access-Controll 관련 헤더가 없음
-> CORS 에러
=> [BUGFIX] #389: 360도 이미지 요청시 CORS에러 수정

frontend/src/components/priceStaticBar/PriceStaticBar.tsx, frontend/src/components/priceStaticBar/PriceStaticSlider.tsx, frontend/src/containers/ModelTypePage/ModelTypeBannerContainer.tsx, frontend/src/containers/ModelTypePage/ModelTypeSelectContainer.tsx
- 모델 pre
- 모델 타입 이미지 contain
- 예산 설정바 설정한 예산 문구 수정
=> [REFACTOR] #420: 전체적인 UI 수정

frontend/src/components/common/banner/Banner.tsx, frontend/src/components/modal/GuideModal.tsx, frontend/src/components/modal/QuoteSummaryModal.tsx, frontend/src/context/ItemProvider.tsx, frontend/src/context/ProgressProvider.tsx, frontend/src/hooks/useSharedInfo.ts, frontend/src/pages/ModelTypePage.tsx
=> [FEAT] #422: 로컬 스토리지 저장

frontend/src/components/modal/SimilarQuoteModal.tsx, frontend/src/components/priceStaticBar/PriceStaticBar.tsx, frontend/src/components/priceStaticBar/PriceStaticSlider.tsx, frontend/src/components/priceStaticBar/SimilarPriceBar.tsx, frontend/src/components/priceStaticBar/SimilarPriceSlider.tsx, frontend/src/utils/constants.ts
- 유사 견적 예산 설정바 UI 수정
- 내 예산 위치도 변경하려했는데 이상해서 일단 스탑
=> [FEAT] #425: 유사 견적 예산 설정바 UI 수정

frontend/src/components/common/navbar/CarSelectContainer.tsx, frontend/src/components/common/navbar/NavBar.tsx, frontend/src/context/ItemProvider.tsx
1. 버그 해결
- 딤드 배경 눌러도 제거 안되는 버그
- 화살표 아이콘 안바뀌는 버그
위 버그 해결했어요
2. 애니메이션 추가 (이상한 것 같아서 동영상 보고 평가좀)
3. nav 바 디자인 변경
=> 종료 버튼 헷갈려서 기획서대로 닫히는 걸로 바꿨어요
=> 그리고 nav 메뉴도 안보이게
애니메이션 추가하긴했는데 좀 이상한 것 같기도?
https://github.com/softeerbootcamp-2nd/A2-CarTag/assets/63107805/462e702b-580f-48a5-84a7-00e6cbfab882
아래는 기획서 대로 변경한 디자인+종료 버튼 기능
=> [FIX] #427: 차종 선택 nav bug

frontend/src/containers/TrimPage/TrimSelectContainer.tsx
```tsx
setSelectedItem({
type: 'SET_OPTIONS',
value: [],
});
```
initDefault에 options 초기화도 추가했어요
=> [FIX] #429: 트림 선택하면 다 초기화

frontend/src/containers/InnerColorPage/InnerColorBannerContainer.tsx, frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx, frontend/src/pages/InnerColorPage.tsx, frontend/src/pages/OuterColorPage.tsx
```tsx
<OuterColorBanner
onMouseUp={handleMouseup}
subtitle={'외장색상'}
title={selectedItem.outerColor.name}
>
```
선택한 외장색으로 배너 이름 바꿨어요
=> [BUG FIX] #431: 외장 색상 이름 선택한 값으로 변경

frontend/src/context/ItemProvider.tsx, frontend/src/hooks/useSharedInfo.ts, frontend/src/pages/ResultPage.tsx
api 변경돼서 코드 수정했습니다.~
```tsx
interface IModelTypeInfo {
modelId: number;
modelName: string;
modelPrice: number;
modelImage: string;
modelTypeName: string;
}
interface IColorInfo {
colorId: number;
colorName: string;
colorImage: string;
colorType: string;
colorPrice: number;
colorBoughtCount: number | null;
colorCarImage: string;
}
export interface ISharedInfo {
trimData: {
carId: number;
trim: string;
carDefaultPrice: number;
};
powertrainData: IModelTypeInfo;
operationData: IModelTypeInfo;
bodyTypeData: IModelTypeInfo;
outerColor: IColorInfo;
innerColor: IColorInfo;
optionList: [
{
optionId: number;
optionName: string;
optionPrice: number;
optionTitle: string;
optionImage: string;
},
];
}
```
=> [FIX] #438: api 변경으로 코드 수정

backend/src/main/java/autoever2/cartag/quotes/dtos/HistoryShortDto.java, backend/src/main/java/autoever2/cartag/quotes/dtos/QuoteRequestDto.java
레디스 저장 오류 버그 수정
- closes: #439
=> [BUG FIX] #439: Quote List Redis관련 에러 해결

backend/src/main/java/autoever2/cartag/service/ColorService.java
int cast로 인해 overflow가 발생하여 퍼센트값 -6이 나오는 버그 해결
- closes: #442
=> [BUG FIX] #439: color int 크기 초과 버그 해결

frontend/src/components/common/navbar/CarSelectContainer.tsx, frontend/src/components/common/navbar/NavBar.tsx, frontend/src/containers/OptionPage/OptionBannerContainer.tsx, frontend/src/containers/TrimPage/TrimBannerContainer.tsx, frontend/src/containers/TrimPage/TrimSelectContainer.tsx, frontend/src/context/ItemProvider.tsx, frontend/src/pages/ModelTypePage.tsx, frontend/src/pages/TrimPage.tsx, frontend/src/reducer/itemReducer.ts, frontend/src/utils/constants.ts
차종 변경 가능합니다.
차 선택만 가능하고 트림 선택은 안돼요.. 에러남
=> [FEAT] #449: 차종 선택 가능

frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx
=> [REFACTOR] 360 이미지 리팩토링

frontend/src/components/modal/ShareModal.tsx, frontend/src/containers/OuterColorPage/OuterColorBannerContainer.tsx
배포 버전에서 clipboard api 안먹는 버그 수정
=> [HOTFIX] : 공유하기 복사 버그 수정

frontend/src/containers/TrimPage/TrimBannerContainer.tsx, frontend/src/containers/TrimPage/TrimSelectContainer.tsx, frontend/src/pages/TrimPage.tsx, frontend/src/utils/constants.ts
https://github.com/softeerbootcamp-2nd/A2-CarTag/assets/63107805/410cb30d-7bd4-485c-8ac8-af0de33f218a
=> [FIX] #456: 르블랑만 다음 단계 가능하게 함

frontend/src/containers/TrimPage/TrimBannerContainer.tsx
=> [FIX] #462: 깜빡임 해결
